on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: seanmckdemo.azurecr.io
        username: ${{ secrets.acr_seanmckdemo_username }}
        password: ${{ secrets.acr_seanmckdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t seanmckdemo.azurecr.io/playground2:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push seanmckdemo.azurecr.io/playground2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_playground2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep playground2a2ab | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace playground2a2ab`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: playground2a2ab
        container-registry-url: seanmckdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_seanmckdemo_username }}
        container-registry-password: ${{ secrets.acr_seanmckdemo_password }}
        secret-name: playground2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: playground2a2ab
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          seanmckdemo.azurecr.io/playground2:${{ github.sha }}
        imagepullsecrets: |
          playground2dockerauth
